name: iOS starter workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    continue-on-error: true
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test
        uses: actions/checkout@v3
      - name: Run tests
        run:  xcodebuild test -project GithubActions.xcodeproj -scheme GithubActions -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' build test
